name: Mezon Voice Bot
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: write
      issues: write
      discussions: write
      actions: write
      deployments: write
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: yarn install
        working-directory: ./MEZON_Vmezon-voice-bot-test-nezonOICE_BOT

      - name: Build
        run: yarn build
        working-directory: ./mezon-voice-bot-test-nezon

      - name: Deploy
        run: yarn start:prod
        working-directory: ./mezon-voice-bot-test-nezon